numpy 常用功能

In [1]:
import numpy as np 

# array的形状和维度

## array的形状--shape

In [2]:
a = np.array([1, 2, 5]) # 产生一个数组
a

array([1, 2, 5])

In [3]:
np.shape(a)

(3,)

In [4]:
a.shape # 变量名.函数名() 等价于 函数名(变量名) a.shape 体现了面向对象的编程思想
        # 不懂的话就跳过进行了, 简单的说:变量名后面加个点就可以对这个变量进行操作,
        # 包括访问变量的属性,或者对这个变量进行函数操作.
        #
        # 比如 a 这个 ndarray 类型的 变量
        # 他有 shape 属性,你可以 a.shape 访问它. 

(3,)

In [5]:
a.mean()  # 再比如 可以 a.mean() 对 a 进行求均值操作.
          # 你可以先打出一个 a 在 打出 一个 点(.) 让后 按下键盘中的 Tab 键,
          # 你的编辑器 就会出现下拉框 你可以流量 a 有什么属性(比如 shape) 
          # 有什么方法(如 mean())
          #
          # 好像 a 是你的对象, 他身高 180 你可以 用 对象.身高 看看他多高
          # 对象.跑步 就是知道了你的对象有跑的能力, 
          # 编辑器写上 '对象.跑步' 点击运行的时候他就真的跑步了
          #  
          # 还是不明白 你就 把 a.mean() 当成 np.mean(a)
          #  
          # np后面的点不是说np是个对象然后怎么怎么,只是调用np库下的函数而已

2.6666666666666665

In [6]:
np.mean(a)

2.6666666666666665

a的shape(形状为):  (3,)

In [7]:
A = np.array([[0.5, 0.2, 0.3],
              [0.3, 0.5, 0.2],
              [0.2, 0.3, 0.5]])
A

array([[0.5, 0.2, 0.3],
       [0.3, 0.5, 0.2],
       [0.2, 0.3, 0.5]])

In [8]:
A.shape

(3, 3)

A的shape(形状为):  (3, 3)

A.shape其实是个元组tuple 可以用访问list的方式访问元组tuple

In [9]:
A.shape[0]

3

为啥a 是(3,) A 是(3,3)? 

当array() 小括号里只有一层[] a就是一维的 两层[[]] 就是两维的




## 维度-ndim

可以输入一下命令查看 维度

In [10]:
a.ndim

1

In [11]:
A.ndim

2

小练习:

试试以下命令 

In [12]:
b = np.array([[1, 2]])
b.shape
b.ndim

2

## 便捷方法---reshape

输入一个矩阵要输入那么多方括号累死我了,有什么快捷的方法?

In [13]:
new_A = np.array([0.5, 0.2, 0.3, 0.3, 
                  0.5, 0.2, 0.2, 0.3, 0.5]).reshape(3, 3)
new_A

array([[0.5, 0.2, 0.3],
       [0.3, 0.5, 0.2],
       [0.2, 0.3, 0.5]])

In [14]:
new_A2 = np.array([0.5, 0.2, 0.3, 0.3,
                   0.5, 0.2, 0.2, 0.3, 0.5]).reshape(1, 9)
new_A2

array([[0.5, 0.2, 0.3, 0.3, 0.5, 0.2, 0.2, 0.3, 0.5]])

new_A new_A2 一样吗?

其实 reshape(n, m) 就是把 array 变成 n * m 维

# 那矩阵乘法如何实现呢

## 先介绍个arange()

In [15]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
B = np.arange(1,10).reshape(3,3)
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

np.arange(9) 与 range(9) 类似 生成 0-8 的数组

np.arange(1,9) 与 range(1,9) 类似 生成 1-8 的数组

In [17]:
np.dot(A, B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

`np.dot()` 实现矩阵相乘

In [18]:
A * B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

A * B 这样是对应乘

# 其他常用函数

## 转置

In [19]:
A.T 

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [20]:
A.transpose() 

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [21]:
A = np.arange(9).reshape(3,3)
np.transpose(A) # 与 A.transpose() 相同

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

`A.T` 与 `A.transpose()`  两个是一样的

## 最大最小

In [22]:
a = np.array([1, 2, 3, 0])
a

array([1, 2, 3, 0])

In [23]:
a.max()

3

In [24]:
max(a)

3

a.max() 与 max(a) 一样的 使用前者程序会更快一些

In [25]:
a.min()

0

In [26]:
a.argmax() # 返回最大值的下标 a 中 a[2] = 3是最大的 所以返回 2

2

In [27]:
a.argmin()

3

## 排序

In [28]:
a = np.array([1, 2, 3, 0])
a.sort()
a

array([0, 1, 2, 3])

In [29]:
a = np.array([1, 2, 3, 0])
np.sort(a)

array([0, 1, 2, 3])

## 迹-trace

In [30]:
print("A = \n", A)
print("A.trace() = \n", A.trace())

A = 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
A.trace() = 
 12


差不多你想要的简单功能 在网上找 应该会找到 

# 切片

绍一下 切片  切片的操作 `np.array` 和 `list` 基本是一样的 

参考网站: 

https://www.jianshu.com/p/15715d6f4dad

In [31]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a[0] # a的第0个 

0

In [33]:
a[-4] # a的倒数第四个

6

In [34]:
a[:] #从左往右 和 a 一样

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a[::-1] #从右往左 倒序

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [36]:
a[1:6] #从 第 1 个索引 到 第 5 个索引 !!!注意: 索引从0开始 到 len(a) - 1 结束 

array([1, 2, 3, 4, 5])

补充一下

In [37]:
len(a) # 查询a 的大小

10

In [38]:
a.size # 同len(a) 面向对象的方法

10

In [39]:
np.size(a) # 同len(a) 调用numpy的函数

10

In [40]:
a[:6] #从头到第5个索引

array([0, 1, 2, 3, 4, 5])

In [41]:
a[6:] #从6到尾巴

array([6, 7, 8, 9])

总结 `a[_:_:_]` `'_'` 这里的意思

`a[这里是开始索引:这里是结束索引:这是step/(几个几个数?)]`

In [42]:
a[1:-1:2] # 猜猜输出多少????

array([1, 3, 5, 7])

可以连续切片

In [43]:
a[:8][2:5][-1:]

array([4])

相当于：

`a[:8]=[0, 1, 2, 3, 4, 5, 6, 7]`

`a[:8][2:5]= [2, 3, 4]`

`a[:8][2:5][-1:] = 4`


# 复制时会出现的问题

 使用 `ndarray` 和 `list` 类型时 用 `=` 时不注意会出现的问题

In [44]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
b = a
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
b[0] = 99
b

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [47]:
a

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

为啥改动b, a也跟着变了?

可以试试这个命令

In [48]:
a is b # a在类型,存储地址上 是 b 吗?

True

In [49]:
id(a) # a存储地址

1307454622096

In [50]:
id(b)

1307454622096

其实为了节省内存 b = a 其实是给 a 起了个小名 叫 b 如同给 你起了个小名,叫那个都是你,修改哪个,都会变


如果是 `b = a.copy()` 这样就正常了

In [51]:
a = np.arange(10)
b = a.copy()
b[0] = 99
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])